### ISSUE TITLE
Add HTML metadata in Vue components with SSR support

### ISSUE THREAD

**Issue by iamrajiv** [nil1729/food-order-app#9]
## Description

Vue Meta is a [Vue.js](https://vuejs.org) plugin that allows you to manage your app's metadata. It is inspired by and works similarly as [`react-helmet`](https://github.com/nfl/react-helmet) for react. However, instead of setting your data as props passed to a proprietary component, you simply export it as part of your component's data using the `metaInfo` property.

**Comment by iamrajiv** [comment]
@nil1729 I want to work on this as Hactoberfest PR.

**Comment by nil1729** [comment]
Go ahead! I assigned it to you.
Happy Coding :smile:
